### PR TITLE
Add an option to generate a pointer to a struct for an object propert…

### PR DESCRIPTION
**Pull request by jmkho-spirent**
…ject that is represented as a struct if it is not a required property.

I made it as a command line option to avoid breaking other people's code.

### CODE REVIEW

**Comment by idubinskiy** [comment]
it's already possible to generate a pointer by including `null` as a possible `type` of the property. For example, [this configuration in a schema](https://github.com/coreos/ignition/blob/96f8aae3675345ef4aef17ece5ed9f6aac7a9fb2/schema/ignition.json#L386) produces [this output in Go](https://github.com/coreos/ignition/blob/96f8aae3675345ef4aef17ece5ed9f6aac7a9fb2/internal/config/types/schema.go#L115).

Does that take care of what you're looking to achieve with this change?

**Comment by jmkho-spirent** [comment]
Ah, I mis-interpreted that and thought it was only possible for primitive types. 

Almost. The only thing I'd prefer not to do is including `null` in the `type` because the property is not `required` and I want that semantic. I can work with this or just fork it.

**Comment by idubinskiy** [comment]
I think the use-case you mention actually makes sense. If you're still OK having this merged, let me know.

**Comment by jmkho-spirent** [comment]
Yes, I'm OK with having this merged.

**Comment by idubinskiy** [comment]
Thanks!

**Pull request merged**
